### ISSUE TITLE
How to create an anndafta object?

### ISSUE THREAD

**Issue by JLiLab** [ElementoLab/utag#1]
I enjoyed reading your paper. UTAG looks very promising. One simple question, how do you create an anndafta object from expression matrix and spatial coordinates?

Thank you,

**Comment by jkim810** [comment]
Thanks for your interest in UTAG. So the [anndata](https://anndata.readthedocs.io/en/latest/) object consists of multiple layers of data. The expression matrix goes into to the X attribute, any metadata associated with cell (cell phenotype labels, etc...) goes into the obs attribute as a pandas dataframe. For UTAG specifically, we recommend putting the spatial coordinates into the obsm attribute with the keyword 'spatial', `adata.obsm['spatial']`, as a numeric numpy array.

Best,
Junbum Kim

**Comment by JLiLab** [comment]
Thank you!
