### ISSUE TITLE
How to Convert IMC Data to UTAG Input (h5ad format)

### ISSUE THREAD

**Issue by rana228** [ElementoLab/utag#3]
Hi, 
@jkim810
I would like to use UTAG but I don't have any experience in Python. 
I have IMC raw data so could you please tell me which file I have to use as input for using UTAG and how to convert that into h5ad format.

Thank you!!

**Comment by jkim810** [comment]
Hello @rana228 ,
The input format (h5ad) for UTAG requires the raw IMC data to be processed into an anndata format, which stores intensity values for each cells in the IMC data. The preprocessing procedure requires cell segmentation from multiplexed images and marker intensity quantification using the generated cell masks. The pipeline I use for this purpose is https://github.com/ElementoLab/imc.

**Comment by rana228** [comment]
Hello @jkim810,
Thank you for your timely help and sorry it took me so long to reply. 
As you suggested I tried running this IMC pipeline (https://github.com/ElementoLab/imc ) but it didn't work with my data so I tried running the sample lung data and it's still not working. So finally I analysed the data using Bodenmiler's pipeline. And now I have Probability Cell masks. As the pipeline suggested by you is not working so I am not sure how to proceed further to get the h5ad format for UTAG. Could you please help me out with this? 
I have exported a file from Histocat too (csv attached). Do you think I can convert this file to h5ad format and use as input in UTAG.
Also I would like to switch to the imc python package for analysing my future IMC data so could you please help me in resolving below mentioned error.
I tried running this command:
# Run pipeline in one step with remote MCD fileMCD_URL=https://zenodo.org/record/4110560/files/data/20200612_FLU_1923/20200612_FLU_1923.mcdimc process $MCD_URLTraceback (most recent call last):                                                                                      

And got following error:
File "/home/rana/anaconda3/bin/imc", line 8, in <module>
sys.exit(main())                                                                                                                          
File "/home/rana/anaconda3/lib/python3.9/site-packages/imc/cli.py", line 35, in main              
return eval(main_args.command)(cmd_args)                                                                          
File "/home/rana/anaconda3/lib/python3.9/site-packages/imc/scripts/process.py", line 121, in main                                              prepare(opts["prepare"] + mcds_s + tiffs_s + txts_s)                                                                 
File "/home/rana/anaconda3/lib/python3.9/site-packages/imc/scripts/prepare.py", line 70, in main                                                mcd_to_dir(**sargs)                                                                                                                  
File "/home/rana/anaconda3/lib/python3.9/site-packages/imc/utils.py", line 690, in mcd_to_dir                                                      write_ometiff(File "/home/rana/anaconda3/lib/python3.9/site-packages/imc/utils.py", line 840, in write_ometifftifffile.imwrite(    TypeError: imwrite() got an unexpected keyword argument 'compress'

Thank you in advance!!

[Sample_ROI1_1_comp_a0.csv](https://github.com/ElementoLab/utag/files/9769028/Sample_ROI1_1_comp_a0.csv)

**Comment by jkim810** [comment]
Hello @rana228 ,
For UTAG, one way going forth from the csv file is to construct a AnnData ([.h5ad](https://anndata.readthedocs.io/en/0.7.8/)) of your own. All the necessary information seems to be already in the csv file. I would put all the metadata into the obs of AnnData object, the numerical feature values into X, and the spatial coordinates of each cells into `adata.obsm['spatial']` as a `numpy` array.

For the imc package, I think the error happened because of a tifffile dependency issue. A short term solution for it would be to downgrade the tifffile version to `tifffile < 2022.4.22` by like `pip install tifffile==2022.3.16`.

**Comment by rana228** [comment]
Hello @jkim810 ,

Thank you so much for your prompt reply. 
**UTAG Input:** As an inexperienced Python user it's a bit difficult to follow your instructions to generate a .h5ad file. Could you please help me with the complete command. It would be of great help for me because I have been struggling with this issue for the past few days.

UTAG is really good package for advance analysis of IMC data and I think it would be much easier for its users if you could add a small section in the UTAG usage manual on how to store processed IMC data like csv or cell masks in Anndata format. This will make its usage much easier.
Many of my friends who have IMC data, they want to use it but couldn't because they don't know how to generate input for UTAG.

**imc Package:** I downgraded it and now the imc package is working.

Thank you in advance!!

**Comment by jkim810** [comment]
Sorry it took a while to respond. Thank you for the suggestion. I currently do not plan to write a usage manual on top of what we provide, but will do so if I get a few more requests.

Following is the code to produce the anndata format.
```{python}
import anndata
import pandas as pd
import numpy as np

df = pd.read_csv('Sample_ROI1_1_comp_a0.csv')

cell_features = ['Cell_127II127Di_I127', 'Cell_131XeXe131Di_Xe131',
'Cell_134XeXe134Di_Xe134', 'Cell_138BaBa138Di_Ba138',
'Cell_190BCKGBCKG190Di_BCKG190', 'Cell_208PbPb208Di_Pb208',
'Cell_80ArArArAr80Di_ArAr80', 'Cell_ATF6Eu151Di_Eu151',
'Cell_CD103Er170Di_Er170', 'Cell_CD15Nd142Di_Nd142',
'Cell_CD163Sm147Di_Sm147', 'Cell_CD204Er166Di_Er166',
'Cell_CD20Dy161Di_Dy161', 'Cell_CD33Yb174Di_Yb174',
'Cell_CD34Lu175Di_Lu175', 'Cell_CD38Yb172Di_Yb172',
'Cell_CD39Er168Di_Er168', 'Cell_CD3Nd145Di_Nd145',
'Cell_CD45ROYb173Di_Yb173', 'Cell_CD45Y89Di_Y89',
'Cell_CD4Gd156Di_Gd156', 'Cell_CD68In113Di_In113',
'Cell_CD69Nd144Di_Nd144', 'Cell_CD8aDy162Di_Dy162',
'Cell_CK7Yb176Di_Yb176', 'Cell_CXCR5Sm149Di_Sm149',
'Cell_CollagenTm169Di_Tm169', 'Cell_DNA1Ir191Di_Ir191',
'Cell_DNA2Ir193Di_Ir193', 'Cell_ECadherinGd158Di_Gd158',
'Cell_EomesDy163Di_Dy163', 'Cell_EpCAMYb171Di_Yb171',
'Cell_FoxP3Gd155Di_Gd155', 'Cell_GranzymeBEr167Di_Er167',
'Cell_HLADRIn115Di_In115', 'Cell_HistoneH3Pt194Di_Pt194',
'Cell_Ki67Nd146Di_Nd146', 'Cell_LYVE1Nd143Di_Nd143',
'Cell_Lag3Gd157Di_Gd157', 'Cell_PD1Ho165Di_Ho165',
'Cell_PDL1Nd150Di_Nd150', 'Cell_RpS6Dy164Di_Dy164',
'Cell_SMAPr141Di_Pr141', 'Cell_TbetGd160Di_Gd160',
'Cell_TCF1Sm152Di_Sm152', 'Cell_TIGITNd148Di_Nd148',
'Cell_TOXEu153Di_Eu153', 'Cell_Tim3Sm154Di_Sm154',
'Cell_bCateninTb159Di_Tb159']

obs_features = ['ImageId', 'CellId', 'Area', 'Eccentricity', 'Solidity',
'Extent', 'EulerNumber', 'Perimeter', 'MajorAxisLength',
'MinorAxisLength', 'Orientation', 'X_position', 'Y_position',
'Percent_Touching', 'Number_Neighbors', 'neighbour_4_CellId1',
'neighbour_4_CellId2', 'neighbour_4_CellId3', 'neighbour_4_CellId4',
'neighbour_4_CellId5', 'neighbour_4_CellId6', 'neighbour_4_CellId7',
'neighbour_4_CellId8', 'neighbour_4_CellId9', 'neighbour_4_CellId10',
'neighbour_4_CellId11', 'neighbour_4_CellId12', 'neighbour_5_CellId1',
'neighbour_5_CellId2', 'neighbour_5_CellId3', 'neighbour_5_CellId4',
'neighbour_5_CellId5', 'neighbour_5_CellId6', 'neighbour_5_CellId7',
'neighbour_5_CellId8', 'neighbour_5_CellId9', 'neighbour_5_CellId10',
'neighbour_5_CellId11', 'neighbour_5_CellId12']

# create anndata
adata = anndata.AnnData(X = df[cell_features], obs = df[obs_features])
# store variables
adata.var.index = cell_features
# store spatial coordinates in obsm layer
adata.obsm['spatial'] = np.array(adata.obs[['Y_position', 'X_position']])

# anndata.concat(adatas: list[anndata.AnnData])
adata.write('SAMPLE_ROI_comp_a0.h5ad')
```

You can then run UTAG with the following script.
```
from utag import utag
utag_results = utag(adata,slide_key=None,max_dist=15,clustering_method='leiden')
```

While this is something you can do on a per slide basis, I also recommend concatenating all the matrices across slides and running UTAG on the joint matrix. In that case, your `slide_key` parameter will be `'ImageID'`.

**Comment by jkim810** [comment]
Hello @rana228 ,

We have also wrote a [tutorial](https://github.com/ElementoLab/utag/blob/main/documentation/UTAG%20Tutorial.ipynb) on how to run UTAG with minimal inputs on your own data. Please feel free to open another issue if you encounter another problem.

Best,
June
