### ISSUE TITLE
Could not construct partition: Weight vector not the same size as the number of edges 

### ISSUE THREAD

**Issue by luglilab** [ElementoLab/utag#4]
Hi,

After installing UTAG following your suggestion I got this error:

"Could not construct partition: Weight vector not the same size as the number of edges." when i digit:

# Run UTAG on provided data
utag_results = utag(
    adata,
    slide_key="roi",
    max_dist=20,
    normalization_mode='l1_norm',
    apply_clustering=True,
    clustering_method = 'leiden', 
    resolutions = [0.05, 0.1, 0.3]
)

I'm using mac-os and this is my env configuration:

# Name                    Version                   Build  Channel
aiohttp                   3.8.3                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
anndata                   0.8.0                    pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
appnope                   0.1.3                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
asttokens                 2.1.0                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
attrs                     22.1.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
bleach                    5.0.1                    pypi_0    pypi
ca-certificates           2022.9.24            h033912b_0    conda-forge
certifi                   2022.9.24                pypi_0    pypi
cffi                      1.15.1                   pypi_0    pypi
charset-normalizer        2.1.1                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
cloudpickle               2.2.0                    pypi_0    pypi
contourpy                 1.0.6                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
dask                      2022.10.2                pypi_0    pypi
dask-image                2022.9.0                 pypi_0    pypi
debugpy                   1.6.3                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
docrep                    0.3.2                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
executing                 1.2.0                    pypi_0    pypi
fasteners                 0.18                     pypi_0    pypi
fastjsonschema            2.16.2                   pypi_0    pypi
fonttools                 4.38.0                   pypi_0    pypi
frozenlist                1.3.1                    pypi_0    pypi
fsspec                    2022.10.0                pypi_0    pypi
h5py                      3.7.0                    pypi_0    pypi
hnswlib                   0.6.2            py38he49a349_5    conda-forge
idna                      3.4                      pypi_0    pypi
igraph                    0.9.9                    pypi_0    pypi
imageio                   2.22.3                   pypi_0    pypi
importlib-metadata        5.0.0                    pypi_0    pypi
importlib-resources       5.10.0                   pypi_0    pypi
inflect                   6.0.2                    pypi_0    pypi
ipykernel                 6.17.0                   pypi_0    pypi
ipython                   8.6.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.0.2                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.2.0                    pypi_0    pypi
jsonschema                4.17.0                   pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            7.4.4                    pypi_0    pypi
jupyter-console           6.4.4                    pypi_0    pypi
jupyter-core              4.11.2                   pypi_0    pypi
jupyter-server            1.21.0                   pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-widgets        3.0.3                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
leidenalg                 0.9.0                    pypi_0    pypi
libblas                   3.9.0           16_osx64_openblas    conda-forge
libcblas                  3.9.0           16_osx64_openblas    conda-forge
libcxx                    14.0.6               hccf4f1f_0    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
libgfortran               5.0.0           10_4_0_h97931a8_25    conda-forge
libgfortran5              11.3.0              h082f757_25    conda-forge
liblapack                 3.9.0           16_osx64_openblas    conda-forge
libopenblas               0.3.21          openmp_h429af6e_3    conda-forge
libsqlite                 3.39.4               ha978bb4_0    conda-forge
libzlib                   1.2.13               hfd90126_4    conda-forge
llvm-openmp               14.0.4               ha654fa7_0    conda-forge
llvmlite                  0.38.1                   pypi_0    pypi
locket                    1.0.0                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.6.2                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
matplotlib-scalebar       0.8.1                    pypi_0    pypi
mistune                   2.0.4                    pypi_0    pypi
multidict                 6.0.2                    pypi_0    pypi
natsort                   8.2.0                    pypi_0    pypi
nbclassic                 0.4.8                    pypi_0    pypi
nbclient                  0.7.0                    pypi_0    pypi
nbconvert                 7.2.3                    pypi_0    pypi
nbformat                  5.7.0                    pypi_0    pypi
ncurses                   6.3                  h96cf925_1    conda-forge
nest-asyncio              1.5.6                    pypi_0    pypi
networkx                  2.8.8                    pypi_0    pypi
notebook                  6.5.2                    pypi_0    pypi
notebook-shim             0.2.2                    pypi_0    pypi
numba                     0.55.2                   pypi_0    pypi
numcodecs                 0.10.2                   pypi_0    pypi
numpy                     1.22.4                   pypi_0    pypi
omnipath                  1.0.5                    pypi_0    pypi
openssl                   1.1.1s               hfd90126_0    conda-forge
packaging                 21.3                     pypi_0    pypi
pandas                    1.5.1                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parmap                    1.6.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
partd                     1.3.0                    pypi_0    pypi
patsy                     0.5.3                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.3.0                    pypi_0    pypi
pims                      0.6.1                    pypi_0    pypi
pip                       22.3               pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
prometheus-client         0.15.0                   pypi_0    pypi
prompt-toolkit            3.0.32                   pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pybind11                  2.10.1                   pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pydantic                  1.10.2                   pypi_0    pypi
pygments                  2.13.0                   pypi_0    pypi
pynndescent               0.5.8                    pypi_0    pypi
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.19.2                   pypi_0    pypi
python                    3.8.2           hd5f0129_7_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python-igraph             0.9.0                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytz                      2022.6                   pypi_0    pypi
pywavelets                1.4.1                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     24.0.1                   pypi_0    pypi
qtconsole                 5.4.0                    pypi_0    pypi
qtpy                      2.2.1                    pypi_0    pypi
readline                  8.1.2                h3899abd_0    conda-forge
requests                  2.28.1                   pypi_0    pypi
scanpy                    1.9.1                    pypi_0    pypi
scikit-image              0.19.3                   pypi_0    pypi
scikit-learn              1.1.3                    pypi_0    pypi
scipy                     1.9.3                    pypi_0    pypi
seaborn                   0.12.1                   pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
session-info              1.0.0                    pypi_0    pypi
setuptools                65.5.0             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
slicerator                1.1.0                    pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlite                    3.39.4               h9ae0607_0    conda-forge
squidpy                   1.2.3                    pypi_0    pypi
stack-data                0.6.0                    pypi_0    pypi
statsmodels               0.13.5                   pypi_0    pypi
stdlib-list               0.8.0                    pypi_0    pypi
terminado                 0.17.0                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2022.3.16                pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h5dbffcc_0    conda-forge
toolz                     0.12.0                   pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 5.5.0                    pypi_0    pypi
typing-extensions         4.4.0                    pypi_0    pypi
umap-learn                0.5.3                    pypi_0    pypi
urllib3                   1.26.12                  pypi_0    pypi
utag                      0.1.1.dev31+g52e535a          pypi_0    pypi
validators                0.20.0                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.4.2                    pypi_0    pypi
wget                      3.2                      pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.3                    pypi_0    pypi
wrapt                     1.14.1                   pypi_0    pypi
xarray                    2022.10.0                pypi_0    pypi
xz                        5.2.6                h775f41a_0    conda-forge
yarl                      1.8.1                    pypi_0    pypi
zarr                      2.13.3                   pypi_0    pypi
zenodo-get                1.3.4                    pypi_0    pypi
zipp                      3.10.0                   pypi_0    pypi
zlib                      1.2.13               hfd90126_4    conda-forge
​

**Comment by jkim810** [comment]
Hello @luglilab,

I would need a bit more clue to help you debug this one. Can you share the full error message?
