### ISSUE TITLE
Edge visualization not working 

### ISSUE THREAD

**Issue by vipulsinghal02** [ElementoLab/utag#7]
Hi, 

When I try to use sc.pl.spatial to plot the data with the parameter `edges = True`, I get the error `'list' object has no attribute 'set_zorder'` in line 511 of the code: `edge_collection.set_zorder(-2)`. Seems like edge_collection is a list, not an axes object. Any help in figuring out this error would be greatly appreciated! 

Best, 
Vipul

Here is the error stack: 

```
AttributeError                            Traceback (most recent call last)
Cell In[84], line 11
      8 single_slide
     10 fig, ax = plt.subplots(1, 1, figsize = (5,5), dpi = 100)
---> 11 sc.pl.spatial(single_slide, color = 'manual_annotations', spot_size = 40, ax = ax, 
     12               title = 'Spatial Connectivity', frameon = False, 
     13               edges = True, neighbors_key = 'spatial_neighbors', 
     14               edges_width = 3, edges_color = 'black')

File ~/miniconda3/envs/utag/lib/python3.8/site-packages/scanpy/plotting/_tools/scatterplots.py:1003, in spatial(adata, basis, img, img_key, library_id, crop_coord, alpha_img, bw, size, scale_factor, spot_size, na_color, show, return_fig, save, **kwargs)
   1000     cmap_img = None
   1001 circle_radius = size * scale_factor * spot_size * 0.5
-> 1003 axs = embedding(
   1004     adata,
   1005     basis=basis,
   1006     scale_factor=scale_factor,
   1007     size=circle_radius,
   1008     na_color=na_color,
   1009     show=False,
   1010     save=False,
   1011     **kwargs,
   1012 )
   1013 if not isinstance(axs, list):
   1014     axs = [axs]

File ~/miniconda3/envs/utag/lib/python3.8/site-packages/scanpy/plotting/_tools/scatterplots.py:420, in embedding(adata, basis, color, gene_symbols, use_raw, sort_order, edges, edges_width, edges_color, neighbors_key, arrows, arrows_kwds, groups, components, dimensions, layer, projection, scale_factor, color_map, cmap, palette, na_color, na_in_legend, size, frameon, legend_fontsize, legend_fontweight, legend_loc, legend_fontoutline, colorbar_loc, vmax, vmin, vcenter, norm, add_outline, outline_width, outline_color, ncols, hspace, wspace, title, show, save, ax, return_fig, **kwargs)
    417 ax.autoscale_view()
    419 if edges:
--> 420     _utils.plot_edges(ax, adata, basis, edges_width, edges_color, neighbors_key)
    421 if arrows:
    422     _utils.plot_arrows(ax, adata, basis, arrows_kwds)

File ~/miniconda3/envs/utag/lib/python3.8/site-packages/scanpy/plotting/_utils.py:511, in plot_edges(axs, adata, basis, edges_width, edges_color, neighbors_key)
    503 for ax in axs:
    504     edge_collection = nx.draw_networkx_edges(
    505         g,
    506         adata.obsm[basis_key],
   (...)
    509         edge_color=edges_color,
    510     )
--> 511     edge_collection.set_zorder(-2)
    512     edge_collection.set_rasterized(settings._vector_friendly)

AttributeError: 'list' object has no attribute 'set_zorder'
```

**Comment by jkim810** [comment]
Hello @vipulsinghal02 ,

Not entirely sure what the exact issue is.

If you wanted to debug your own code, first things I would look into here are whether the proper `spatial_neighbors` keys are stored. Lookin a bit into the `nx.draw_networkx_edges` functions, it seems like the proper behavior is to return a matplotlib `LineCollection` object.

A convenient alternative is to use the `scatter_spatial` function from [`squidpy`](https://squidpy.readthedocs.io/en/stable/auto_examples/graph/compute_spatial_neighbors.html#sphx-glr-auto-examples-graph-compute-spatial-neighbors-py).

```{python}
sq.gr.spatial_neighbors(adata, n_neighs=10, coord_type="generic")
_, idx = adata.obsp["spatial_connectivities"][420, :].nonzero()
idx = np.append(idx, 420)
sq.pl.spatial_scatter(adata[idx, :], shape=None, color="cell type", connectivity_key="spatial_connectivities", size=100)
```
You can look up their documentation for more details. I would run these on a per region/area of interest.

**Comment by vipulsinghal02** [comment]
Figured out the issue: If the radius parameter in `sq.gr.spatial_neighbors` is too small for any neighbours to be called out, then this occurs. In my case, seems like the minimum distance between Visium spots needs to be set to 138, while the default I was using was 15. In my case, turns out at the default radius, I was probably just doing non-spatial clustering. 

I think some warning or displayed message should be added (in one of the functions that you control, say `utag()`) to alert the user that the spatial graph contains no edges, since a priori, for a new dataset, it may not be obvious that the user has not picked a large enough distance threshold for edges to appear. And if the user is blindly implementing the tutorial (as one sometimes does!), they may never realize the error. 

Side question: would you recommend running UTAG exactly as the tutorial describes, or using the usual standard practices in scRNA seq analysis preprocessing (for example, if working with Visium data, do the usual cell and gene filtering, total count normalization, highly variable gene selection, zscaling, PCA, etc)?

**Comment by jkim810** [comment]
Thanks for the suggestion. Will incorporate this in a future update.

So I would suggest that it generally is a good idea to do all the standard practices in scRNA seq analysis. It is something that we do as well on our IMC datasets.

Nevertheless, I should also let you know that we have not really tested our method on Visium, as it does not come at single cell resolution. Although the method can be applied on Visium, I would be surprised if it did work well because each of the spots in the order of tens of cells.
