### ISSUE TITLE
Raw image data access

### ISSUE THREAD

**Issue by miaecle** [ElementoLab/utag#8]
Hi!

Thank you so much for providing the codes and data inputs for UTAG!

I am especially interested in the healthy lung data and the AnnData files are extremely helpful. I am wondering if there is any way to access the raw images for the 26 regions stored in the "healthy_lung_adata.h5ad"? I am hoping to directly look at the cell morphology and add some additional analysis.

Also just want to clarify, I am looking at Table E10 of the source publication https://doi.org/10.1164/rccm.202207-1384OC. And the list of IMC biomarkers seem to be shorter than what is available in the h5 file (26 biomarkers).

**Comment by afrendeiro** [comment]
Hi Zhenqin,

Thanks for the interest in our paper/datasets.

Unfortunately we don't have access to the raw data from that publication as
in that paper IMC provided only a small supporting role and they were not
made available.

I would suggest you contact the corresponding author of that paper and see
if they are willing to share them with you or better, make the data fully
publicly available.

Best wishes,
André

**Comment by miaecle** [comment]
Hi André, Thank you for your answer! Yeah no problem, I will go ahead and email them about the request!
